### PR TITLE
Typography sync

### PR DESCRIPTION
**Pull request by allenkepler-finastra**

### CODE REVIEW

**Review by BeataKr — CHANGES_REQUESTED** [review]
On the test app, I can see properly built typography - you can always build your local by `npm run dev` 
PS checking other impact of changes
image

**Comment by BeataKr** [comment]
parially done under https://github.com/Finastra/fds-angular/pull/66 
as we discussed please create PR with fixed font-family: Roboto

**Comment by allenkepler-finastra** [comment]
this has been merged in via another PR right?

**Comment by allenkepler-finastra** [comment]
added https://github.com/Finastra/fds-angular/pull/68 to add  font-family: Roboto

**Pull request closed without merging**
